{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lovelysystems",
    "module": "lovely-db-testing",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lovely-db-testing-0.1.0.jar",
          "url": "lovely-db-testing-0.1.0.jar",
          "size": 27544,
          "sha512": "334a59470bd00f9d29ef81f10bf9be2d395810cb6c223603af38667192b92049298f55482f8e89f0690821f87b061a7cb19e3b357f209b580c22bd9e574845e0",
          "sha256": "b4e4de99603dde92ed43b31b5cedec55fe063190ca09a098ff123c0bf9ee1374",
          "sha1": "81b98e60b2fde65ed467fed27ec7d2928e99f43c",
          "md5": "0e4700dd53ba3b4fb1a84b4197cf3304"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.testcontainers",
          "module": "testcontainers",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "lovely-db-testing-0.1.0.jar",
          "url": "lovely-db-testing-0.1.0.jar",
          "size": 27544,
          "sha512": "334a59470bd00f9d29ef81f10bf9be2d395810cb6c223603af38667192b92049298f55482f8e89f0690821f87b061a7cb19e3b357f209b580c22bd9e574845e0",
          "sha256": "b4e4de99603dde92ed43b31b5cedec55fe063190ca09a098ff123c0bf9ee1374",
          "sha1": "81b98e60b2fde65ed467fed27ec7d2928e99f43c",
          "md5": "0e4700dd53ba3b4fb1a84b4197cf3304"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lovely-db-testing-0.1.0-sources.jar",
          "url": "lovely-db-testing-0.1.0-sources.jar",
          "size": 4223,
          "sha512": "4d101895c7555d5e6c71c9e5cbbce79b85884352c083e5c0fd5fdf07a9a79d7be0fa326a766c56f30f97f79a8317b47b705ca43743c33615ac90154ac3f16705",
          "sha256": "9fbfa018e507a508a02da864070c2bf48eb89392d866109659306705c8e95a6c",
          "sha1": "a04acd255d8c8770726d439a217667bf301cf1f6",
          "md5": "a170bb1c51c4e0d633b137d3c830cdca"
        }
      ]
    }
  ]
}
